services:
  auth:
    image: auth
    container_name: auth
    restart: always
    env_file:
      - .env
    build: .

  postgres_auth:
    image: postgres:17.4
    container_name: postgres_auth
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./infra/volumes/postgres_auth:/var/lib/postgresql/data
    restart: unless-stopped

  redis_auth:
    image: redis:7.4.1
    container_name: redis_auth
    command:
      redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./infra/volumes/redis:/data
      - ./infra/configs/redis:/usr/local/etc/redis
    restart: unless-stopped

  nginx_auth:
    container_name: nginx_auth
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./infra/configs/nginx_auth/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/configs/nginx_auth/site.conf:/etc/nginx/conf.d/site.conf:ro
    # ports:
    #   - "80:80"
