services:
  atopacake_api:
    image: atopacake_api
    container_name: atopacake_api
    restart: always
    env_file:
      - .env
    build: .

  postgres_atopacake_api:
    image: postgres:17.4
    container_name: postgres_atopacake_api
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./infra/volumes/postgres_atopacake_api:/var/lib/postgresql/data
    restart: unless-stopped

  redis_atopacake_api:
    image: redis:7.4.1
    container_name: redis
    command:
      redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./infra/volumes/redis:/data
      - ./infra/configs/redis:/usr/local/etc/redis
    restart: unless-stopped

  nginx_atopacake_api:
    container_name: nginx_atopacake_api
    image: nginx:1.25.5
    restart: always
    volumes:
      - ./infra/configs/nginx_atopacake_api/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./infra/configs/nginx_atopacake_api/site.conf:/etc/nginx/conf.d/site.conf:ro
    # ports:
    #   - "80:80"
